---
- name: Provision Instances
  hosts: localhost
  gather_facts: no
  tags:
    - manage_instances
  vars:
    teardown: false
  tasks:
#  - include_role:
#      name: "check_setup"
  - include_role:
      name: "manage-{{ instance_loc }}-instances"

- name: Configure Active Directory Domain Controller
  hosts: windows_domain_controllers 
  gather_facts: yes
#  vars_files:
#    - [ 'vars/custom.yml', 'vars/main.yml' ]
  tags:
    - windows_ad_controller
  roles:
    - windows-ad-controller

- name: Configure Windows Servers
  hosts: windows
  gather_facts: True
#  vars_files:
#    - [ 'vars/custom.yml', 'vars/main.yml' ]
  tags:
    - windows_hosts
  roles:
    - windows-common

- name: Configure Windows Workstation
  hosts: windows_workstations
  gather_facts: True
#  vars_files:
#    - [ 'vars/custom.yml', 'vars/main.yml' ]
  tags:
    - windows_workstation
  roles:
    - windows-common
    - windows-workstation

- name: all hosts ip details
  hosts: all
  gather_facts: True
  tasks:
  
  - name: Print public ip 
    debug:
      var: "{{hostvars[inventory_hostname].public_ip}} {{ inventory_hostname }}"
